library core;

export 'package:equatable/equatable.dart';
export 'styles/colors.dart';
export 'styles/text_styles.dart';
export 'utils/constants.dart';
export 'utils/exception.dart';
export 'utils/failure.dart';
export 'utils/state_enum.dart';
export 'package:core/utils/network_info.dart';
export 'package:movie/presentation/pages/home_movie_page.dart';
export 'package:movie/presentation/pages/popular_movies_page.dart';
export 'package:movie/presentation/pages/top_rated_movies_page.dart';
export 'package:movie/presentation/pages/watchlist_movies_page.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:flutter_rating_bar/flutter_rating_bar.dart';
export 'package:http/http.dart';
export 'package:provider/provider.dart';
export 'package:core/utils/ssl_pinning.dart';
